### ISSUE TITLE
webvpn 的 URL 编码方式更新

### ISSUE THREAD

**Issue by hexone2086** [w43322/neu-webvpn-anysite#1]
例如，东大主页（www.neu.edu.cn）的访问地址变更为：
`https://webvpn.neu.edu.cn/http/62304135386136393339346365373340a7f6b37184c05393f71c7e3d850b`
而按照原来方式的编码为：
`https://webvpn.neu.edu.cn/http/77726476706e69737468656265737421e7e056d229357d1e7b0c9ce29b5b`

在可访问资源中摘取了几个：
`62304135386136393339346365373340a7f6b37184c05393f71c7e3d850b`
`62304135386136393339346365373340a7f6b37189cb4dd4bc166e67`
`62304135386136393339346365373340a0e0b72cc4cb43c8bc1d6f66c806db`
`62304135386136393339346365373340b8efea2c99c94fdfe019796ac806da8a`
`62304135386136393339346365373340a7f6b37189c44bdfe0116f74834bda9573`
`62304135386136393339346365373340b1e2a73a99d608defe19797a9004c1827be575c1`
`62304135386136393339346365373340a7f6b3719dc448dbf3166c778711d4c92c560e7051ce`
`62304135386136393339346365373340a7f6b37186cc4493fc1d7e3d8301c0c9b65f`

**Comment by w43322** [comment]
收到，抽空看一下

**Comment by w43322** [comment]
已更新，感谢反馈，可以试一下。

**Comment by w43322** [comment]
https://tang-keke.tk/webvpn 同步更新了

**Comment by hexone2086** [comment]
工作正常，非常感谢！
